name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: setup-go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: go.mod
      - name: test
        run: go run gotest.tools/gotestsum@latest --format github-actions
      - name: lint
        uses: golangci/golangci-lint-action@e7fa5ac41e1cf5b7d48e45e42232ce7ada589601 # v9.1.0
        with:
          version: latest
  test-container:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Build docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          push: false
          load: true
          tags: score-radius:test
          build-args: |
            "VERSION=test"
      - name: Test app
        run: |
          make test-app
      - name: Test container image
        run: |
          make test-container
  test-radius:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Install Radius CLi
        run: |
          wget -q "https://raw.githubusercontent.com/radius-project/radius/main/deploy/install.sh" -O - | /bin/bash
      - name: Create Kind cluster
        run: |
          make setup-kind-cluster
      - name: Test
        run: |
          kubectl get pods -n radius-system
          make build
          make deploy-podinfo-to-radius
